### ISSUE TITLE
Please Rename Your Module

### ISSUE THREAD

**Issue by muellerc** [fjoppe/Camel.Net#1]
Your module uses the Apache Software Foundation "Camel" trademark improperly. Can you rename it please?

On behalf of the Camel PMC,
Christian Müller
VP, Apache Camel

**Comment by fjoppe** [comment]
Hi Christian, is the name protected? I had no idea. I'll come back on this.

**Comment by johnament** [comment]
@fjoppe please review http://www.apache.org/foundation/marks/list/#projects

**Comment by fjoppe** [comment]
I'll rename this project. Won't happen by tomorrow because it involves some work (repo+code) and this is a spare-time thing. I'll try this weekend, or the next.

**Comment by muellerc** [comment]
Hi Frank,

thanks for our understanding and prompt reaction.
There are a few more places where you are using "Camel.Net", like in the README.md file.

Regards,
Christian

**Comment by fjoppe** [comment]
Hi Chris, I know. I haven't finished the renaming work yet; code, namespaces, readme's and more. I'll come back when I think it is finished,

**Comment by fjoppe** [comment]
Ok, the renaming process has now finished.

**Comment by muellerc** [comment]
Thanks a lot.
